package domain;

public enum TipoPaciente {
	PERROS, GATOS, CONEJOS, HAMSTERS, COBAYAS, HURONES, CHINCHILLAS, RATONES, RATAS, ERIZOS,LOROS, CANARIOS, PERIQUITOS,SERPIENTES, LAGARTOS, 
	TORTUGAS, RANAS, SALAMANDRAS, CABALLOS, PONIS, BURROS, CABRAS, OVEJAS, VACAS, CERDOS, 
	GALLINAS, PATOS, PAVOS, HALCONES, ÁGUILAS, MIRLOS, ARAÑAS, ESCORPIONES, TUCANES, CACATÚAS, 
	MARMOTAS, MUSARAÑAS,  ALPACAS, LLAMAS, DELFINES, FOCAS, PINGÜINOS, ELEFANTES, JIRAFA, RINOCERONTES, 
	HIPOPÓTAMOS, LEONES, TIGRES, OSOS, ZORROS, MAPACHES, ZARIGÜEYAS, NUTRIAS, MURCIÉLAGOS, 
	KOALAS, CANGUROS, ORNITORRINCOS, EQUIDNAS, QUOKKAS, WOMBATS,XSPULPOS, CALAMARES, MEDUSAS,ESTRELLAS, BALLENAS 
	

}
