package domain;

public enum TipoPaciente {
	 	PERRO, GATO, CONEJO, HAMSTER, COBAYA, HURON, CHINCHILLA, RATON, RATA, ERIZO, LORO, CANARIO, PERIQUITO,
	    SERPIENTE, LAGARTO, TORTUGA, RANA, SALAMANDRA, CABALLO, PONI, BURRO, CABRA, OVEJA, VACA, CERDO,
	    GALLINA, PATO, PAVO, HALCÓN, ÁGUILA, MIRLO, ARAÑA, ESCORPIÓN, TUCÁN, CACATÚA, MARMOTA, MUSARAÑA,
	    ALPACA, LLAMA, DELFÍN, FOCA, PINGÜINO, ELEFANTE, JIRAFA, RINOCERONTE, HIPOPÓTAMO, LEÓN, TIGRE, OSO,
	    ZORRO, MAPACHE, ZARIGÜEÑA, NUTRIA, MURCIÉLAGO, KOALA, CANGURO, ORNITORRINCO, EQUIDNA, QUOKKA, WOMBAT,
	    PULPO, CALAMAR, MEDUSA, ESTRELLA, BALLENA
}
