package domain;

public enum TipoPaciente {
    ARAÑA, ALPACA, ÁGUILA, BALLENA, BURRO, CABALLO, CABRA, CACATÚA, CALAMAR, CANARIO, CANGURO, CERDO, CHINCHILLA,
    CONEJO, DELFÍN, ELEFANTE, ERIZO, ESCORPIÓN, ESTRELLA, FOCA, GALLINA, GATO, HAMSTER, HALCÓN, HIPOPÓTAMO,
    HURON, JIRAFA, KOALA, LAGARTO, LEÓN, LLAMA, LORO, MAPACHE, MEDUSA, MIRLO, MARMOTA, MURCIÉLAGO, MUSARAÑA,
    NUTRIA, OVEJA, ORNITORRINCO, OSO, PAVO, PATO, PERIQUITO, PERRO, PINGÜINO, PONI, PULPO, QUOKKA, RANA, RATÓN,
    RATA, RINOCERONTE, SALAMANDRA, SERPIENTE, TIGRE, TORTUGA, TUCÁN, VACA, WOMBAT, ZARIGÜEÑA, ZORRO
}