package domain;

public enum TipoMaquinaria {
	RAYOS_X, ECOGRAFO, ESTETOSCOPIO_VETERINARIO, 
	EQUIPO_DE_LABORATORIO, AUTOCLAVE, MONITOR_DE_SIGNOS_VITALES,
	INTRUMENTAL_QUIRURJICO,BOMBA_DE_INFUSION, JAULAS, MOBILIARIO, 
	EQUIPO_DE_ESTERILIZACION, BASCULA_VETERINARIA, MATERIAL_DE_LIMPIEZA
	

}
